### ISSUE TITLE
[L10N][FRA][Web Fonts extension]: Unlocalized string for connecting Web Fonts Server failure.

### ISSUE THREAD

**Issue by julieyuan** [adobe/brackets-edge-web-fonts#100]
Steps:
​1. Launch the Brackets
2. Click "File" > "Install Extension..."
3. Input the URL of the Edge Web Fonts zip package
4. Click the "Install" button​
5. Disconnect OS network and hover the mouse on the Web fonts icon.

Result:
​The string is unlocalized.

Expected:
​It should be localized

Env: Win
Build: 0.25.0-7369

Screenshot:
![web font-unlocal string-fra](https://f.cloud.github.com/assets/4251563/495055/a62c0624-bbb3-11e2-9ac0-8acd1904f6e5.png)

**Comment by iwehrman** [comment]
@ryanstewart Are you OK with the text of this message in English?

**Comment by ryanstewart** [comment]
Yup! Looks good to me!

**Comment by iwehrman** [comment]
@Zhuyun Can you help us out with this one for Sprint 4?

**Comment by julieyuan** [comment]
Checked this issue in latest build  0.26.0-7736. This string has already been localized. So closed it . Please refer to snapshot: 
![100 fixed](https://f.cloud.github.com/assets/4251563/583015/2fe4592e-c8d5-11e2-8043-44890c72802e.png)
