### ISSUE TITLE
Font script insert dialog has a weird input border

### ISSUE THREAD

**Issue by iwehrman** [adobe/brackets-edge-web-fonts#112]
![border](http://f.cl.ly/items/2v3W2i2n2G1m0f470q0M/Screen%20Shot%202013-05-17%20at%205.00.28%20PM.png)

This is inconsistent with all the other input borders, which are bold and sharp.

**Comment by njx** [comment]
The fuzzy blue border is the standard Mac focus ring. I bet this is a `<textarea>`, and I think @larz0 only crisped up the focus ring for `<input>`. We should just apply that to `<textarea>` as well.

**Comment by iwehrman** [comment]
Submitted pull adobe/brackets#3922 to fix. With that patch, the dialog will look like this: 

![3922](http://f.cl.ly/items/1W0C01000K370k01342H/Screen%20Shot%202013-05-20%20at%2010.49.32%20AM.png)

**Comment by larz0** [comment]
Schweet. BTW I'm wondering if we can replace:

"To ensure that fonts are properly loaded, you must add a script tag to your HTML. Copy the following script tag and paste it into all HTML files that reference this CSS file:"

with

"Add this JavaScript tag to the &lt;head&gt; of your website's HTML that reference this CSS file:" (similar to https://edgewebfonts.adobe.com/fonts)

**Comment by iwehrman** [comment]
I too think the instructions are worded poorly. My suggestion might be something like the following: 

Edge Web Fonts are loaded with JavaScript. To use the fonts you've chosen, paste the following script tag into HTML files that reference this CSS file.

It's not necessarily a good idea to put them script tag in the `<head>`, so I don't think we should recommend that explicitly.

@njx Any thoughts?

**Comment by larz0** [comment]
Web fonts are the only JS that should go in the &lt;head&gt; instead of the bottom because of Flash of Unstyled Text aka FOUT.

**Comment by iwehrman** [comment]
@larz0 Oh, right, good point! I'm going to open a fresh issue to track the wording in this dialog. 

In the meantime, since adobe/brackets#3922 has been merged, I'm closing this one out.
