### ISSUE TITLE
Webfonts Icon No Longer Appears in Instructions

### ISSUE THREAD

**Issue by ryanstewart** [adobe/brackets-edge-web-fonts#115]
It looks like with the icon change we lost the icon on the Webfonts Instruction page

![screenshot_5_21_13_2_30_am](https://f.cloud.github.com/assets/45450/540853/1d0767ca-c1f9-11e2-8971-bcaf35c911e9.png)

**Comment by ryanstewart** [comment]
Marking this high priority because I think it's pretty critical to make sure people know what to click. (Hopefully that's not overkill)

**Comment by iwehrman** [comment]
Whoopsie daisy. I'll fix it today.

**Comment by iwehrman** [comment]
Closed by #116.
