### ISSUE TITLE
Update the instructions picture again

### ISSUE THREAD

**Issue by iwehrman** [adobe/brackets-edge-web-fonts#117]
With @couzteau big menu update, the instructions image is again out of date. It currently looks like this:
![instructions](http://f.cl.ly/items/0A3N0t3l433m0l1A2i1D/Screen%20Shot%202013-05-21%20at%2010.33.13%20AM.png)
But the menu looks like this: 
![menu](http://f.cl.ly/items/0A2g1J0O2n2Z3Z0X1w1F/Screen%20Shot%202013-05-21%20at%2010.40.10%20AM.png)

@ryanstewart should have the appropriate layered files.

**Comment by iwehrman** [comment]
Marking low priority. I'd like to fix it, but I don't think anyone will be terribly confused until we do.

**Comment by iwehrman** [comment]
Assigning to @larz0.

**Comment by larz0** [comment]
@iwehrman Here's the retina image so just half the dimension in <img>: http://cl.ly/image/1K3D1c1s0P0w.

We should make the  paragraph line-height the same as the list-item line-height because it's slightly to big.

![edgewebfonts_initialdialog_001](https://f.cloud.github.com/assets/1495261/551969/2f85cbca-c33a-11e2-984b-c598617c6cd9.png)

**Comment by iwehrman** [comment]
@larz0 Are you advising that I just ship the retina image and let the browser resize it? Or that I resize it first in PS?

**Comment by iwehrman** [comment]
This image also needs to be updated in French. @ryanstewart, any thoughts about whether I should hold off on updating this image?

**Comment by larz0** [comment]
@iwehrman for an instructional image I think it's okay to let the browser resize it. I'll work on the French image.

**Comment by larz0** [comment]
@iwehrman here's the french image: http://cl.ly/image/1H330q083I1B

**Comment by iwehrman** [comment]
Fixed by #134.
