### ISSUE TITLE
[XD] It's safe to remove "Adobe" from the extension title

### ISSUE THREAD

**Issue by larz0** [adobe/brackets-edge-web-fonts#124]
@iwehrman I asked Joyce Solano and she said it's ok to remove "Adobe" from the extension title. This is the same for Edge Inspect and I'll create a separate issue for that.

**Comment by ryanstewart** [comment]
Thanks for checking on this @larz0, this is way better :+1:

**Comment by larz0** [comment]
Now I can finally sleep at night, sort of.

**Comment by iwehrman** [comment]
Fixed #125.
