### ISSUE TITLE
[UI] Font Selection Border Color

### ISSUE THREAD

**Issue by larz0** [adobe/brackets-edge-web-fonts#127]
Right now the border is orange:
![screen shot 2013-05-23 at 4 25 09 pm](https://f.cloud.github.com/assets/1495261/557896/8954d0b2-c400-11e2-9c4f-de2f4f4ac593.png)

It should be blue (#288EDF):
![screen shot 2013-05-23 at 4 24 41 pm](https://f.cloud.github.com/assets/1495261/557897/9a113aa8-c400-11e2-9b01-715b0fb2e470.png)

**Comment by couzteau** [comment]
Is there a larger EWF UI overhaul coming up? Should we wait?

**Comment by larz0** [comment]
@couzteau There are talks but it hasn't been designed. We should correct this since orange is not really being used in the visual language (warnings are orange but that's about it).

**Comment by iwehrman** [comment]
I will fix this.

**Comment by larz0** [comment]
![1kx2zh1tv6j8vog](https://f.cloud.github.com/assets/1495261/581113/fcb50d98-c896-11e2-9d8a-ca4af114719b.gif)

**Comment by iwehrman** [comment]
Fixed by #131.
