### ISSUE TITLE
[L10N][French][Edge Web Fonts]: The brand for extension title should be consistent with ENU.

### ISSUE THREAD

**Issue by julieyuan** [adobe/brackets-edge-web-fonts#135]
Steps:
1. Launch Edge Code.
2. Click the EWF icon on the top right of Edge Code. It will pop up a page and close it.
3. Open a CSS file , and input  font-family, press Ctrl+Space to show the submenu.
4. Click browse Web Fonts....

Results:
The brand is "Adobe Edge Web Fonts", which is inconsistent with ENU "Edge Web Fonts"

Expected:
It should be consistent with ENU brand.

ENV: Win8 FRA
Build: 0.94.0-359071970 

Screenshots:

![web fonts-adobe-enu](https://f.cloud.github.com/assets/4251563/583784/c8b6e312-c900-11e2-92ea-219b424c8c90.png)
![web fonts-adobe-enu2](https://f.cloud.github.com/assets/4251563/583785/c8eea248-c900-11e2-8caf-cb25619fabc8.png)

**Comment by iwehrman** [comment]
I don't see this on master: 

![help](http://f.cl.ly/items/2X140r35020r2C2J1V1n/Screen%20Shot%202013-06-17%20at%201.51.20%20PM.png)

![picker](http://f.cl.ly/items/0e3C1s0R173t2Q1w0d13/Screen%20Shot%202013-06-17%20at%201.52.56%20PM.png)

**Comment by julieyuan** [comment]
Checked this issue in Brackets 0.27.0.8106 and Edge Code 0.94.0-359080676, it doesn't reproduce. I think it is fixed in latest build. So close it.
