### ISSUE TITLE
'Browse Web Fonts' not working

### ISSUE THREAD

**Issue by ghost** [adobe/brackets-edge-web-fonts#140]
When I click 'Browse Web Fonts' nothing appears.
![capturar](https://f.cloud.github.com/assets/2386029/629220/bef63d3c-d134-11e2-81df-eda47f6675eb.png)

**Comment by iwehrman** [comment]
There have been some recent updates to accommodate breaking changes in Brackets. We probably were too aggressive about pushing those changes out to master. Are you using the Brackets Sprint 25 build?

**Comment by ghost** [comment]
Well, I'm using: sprint 25 experimental version 0.25.0-7701 (master e664a00d0)

**Comment by iwehrman** [comment]
If you're git-savvy, you might try pulling the [Brackets JavaScript files from source](https://github.com/adobe/brackets) and running the current version of EWF from there. Or, alternately, try rolling back EWF to the slightly older [Edge Code Preview 4 branch](https://github.com/adobe/brackets-edge-web-fonts/tree/edge-code-preview-4-branch). If neither of those fixes the problem, please let me know. Or you can just wait a few days for Brackets Sprint 26 builds to be released, at which time all should become well :)

**Comment by iwehrman** [comment]
Closing because this is fixed as of Brackets Sprint 26.
