### ISSUE TITLE
[L10N][German]: Overlocalized Edge Web Fonts page and tooltip in German OS.

### ISSUE THREAD

**Issue by julieyuan** [adobe/brackets-edge-web-fonts#142]
Steps:
1. Go to web page: creative.adobe.com
2. Download Edge Code Preview 4 release build.
3. Install Edge Code and launch it.
4. Hover the mouse on the Edge Web Fonts icon on the top right of Edge Code, then click the icon to bring up Edge Web Fonts page

Results:
The tooltip for the icon and the pop up page are overlocalized.

Expected:
They should stay in English on non-French OSes.

ENV: German Mac 10.8 and Windows 7/8

Please refer to snapshots:

![bildschirmfoto 2013-06-18 um 3 43 39 am](https://f.cloud.github.com/assets/4251563/668066/94a355ce-d805-11e2-957d-4240c1ce87a6.png)
![bildschirmfoto 2013-06-18 um 3 45 36 am](https://f.cloud.github.com/assets/4251563/668067/94e5b8f6-d805-11e2-9df3-dc8be01a9722.png)

**Comment by iwehrman** [comment]
Uh, do we actually want to turn off German localization here? I agree that it would be better if the whole product were localized, but might something be better than nothing? Any opinion, @pthiess @couzteau @ingorichter?

**Comment by bchintx** [comment]
submitted fix as Pull Request #146.

Removed German ("de") from master list of supported language translations (ie. nls/strings.js).  Left the actual translated content in-place though for future use.  When we want to re-enable the German translation (ie. when the rest of Edge Code supports German), then we can just re-add this one line.

**Comment by couzteau** [comment]
verified fix. Will go out with the next pre release drop

**Comment by julieyuan** [comment]
Fixed in Brackets master 0.28.0.8522 build. Not fixed in Edge Code 0.95.0-359081203 build yet. Will check it again in later Edge Code build. Here is the snapshot in master:
![bildschirmfoto 2013-07-24 um 10 16 03 pm](https://f.cloud.github.com/assets/4251563/853696/3e57234c-f4ea-11e2-8e57-2aa0407353d1.png)

**Comment by bchintx** [comment]
Re-opening this issue.  Per Julie's comment, please note that this fix won't be available until EWF is merged into EdgeCode via this pull request: https://git.corp.adobe.com/edge/edge-code/pull/190

**Comment by bchintx** [comment]
Pull Request 190 has been merged.  Confirmed that this is now fixed in Edge Code master branch, and should be available to Julie in the next build.

@julieyuan please close this issue when you've confirmed the fix.  Thanks!

**Comment by julieyuan** [comment]
Fixed in Edge Code  build 0.95.0-359081293. Please refer to snapshot:
![bildschirmfoto 2013-07-25 um 7 12 20 pm](https://f.cloud.github.com/assets/4251563/860164/fef90aac-f599-11e2-9d56-2c9dd0eda3cb.png)
