### ISSUE TITLE
[Core][Blackletter fonts]: Name of UnifrakturMaguntia fonts is trucated on the Edge Web Fonts dialog.

### ISSUE THREAD

**Issue by julieyuan** [adobe/brackets-edge-web-fonts#150]
Steps:
1. Launch Brackets.
2. Install Edge Web Fonts extension into Brackets.
3. Open a css file and input `font-family:` to select `Browse Web Fonts...` from the code hints.
4. Click Blackletter tab on the Edge Web Fonts dialog and click the font UnifrakturMagunitia( the last one).

Result:
Its name cannot appear completely.

Expected:
Its name should display well.

ENV: MAC 10.8 and Win8.1 English OS
Build: 0.30.0-8827

Snapshot:
Please refer to snapshot for details:
![11](https://f.cloud.github.com/assets/4251563/1007112/fbccb5c0-0afe-11e3-898a-a269132cd92e.png)
![22](https://f.cloud.github.com/assets/4251563/1007113/01d68450-0aff-11e3-8b9e-d668824c5281.jpg)

**Comment by iwehrman** [comment]
Good catch, @julieyuan! Nominating for Sprint 9.

**Comment by couzteau** [comment]
fixed. closing

**Comment by julieyuan** [comment]
checked this issue with latest extension build. It is fixed. Here is the snapshot: 
![1111](https://f.cloud.github.com/assets/4251563/1155080/ef129454-1f61-11e3-9aad-df1042b40fe1.png)
