### ISSUE TITLE
[L10N][toolbar icon][French]: The EWF toolbar icon is not at the end of buttons div when launching it first time.

### ISSUE THREAD

**Issue by julieyuan** [adobe/brackets-edge-web-fonts#152]
Steps:
1. Install Edge Code on a clean French OS.
2. Launch Edge Code.

Result:
The EWF toolbar icon is at not at the end of buttons div.

Expected:
According pull request #151, it should be at the end of bottons div.

Notes:
This issue only reproduce at the first time launching. If you reload Edge Code , it will not happen.

ENV: MAC 10.9 and Win7 x64 French OS
Build: 0.96.0-359082271

Snapshots:
Please refer to snapshots for details:
![fra-ewf icon](https://f.cloud.github.com/assets/4251563/1086262/bb052168-15f7-11e3-8647-89d76d995a9a.jpg)
![enu-ewf icon](https://f.cloud.github.com/assets/4251563/1086263/bb2eb528-15f7-11e3-9c95-efb499c003d9.jpg)

**Comment by iwehrman** [comment]
It doesn't actually need to be the very last icon, it just needs to be below the Brackets-standard Live Preview and Extension Manager icons. So, closing this as not-a-bug.

**Comment by julieyuan** [comment]
Ok, got it. Thanks.
