### ISSUE TITLE
Terms of Use link doesn't work in Brackets sprint 31

### ISSUE THREAD

**Issue by iwehrman** [adobe/brackets-edge-web-fonts#154]
Found by @larz0. It's entirely possible that whatever changed in Brackets that broke this broke other things too, so we should do a little more testing than usual when we (Edge Code) does our next merge.

**Comment by iwehrman** [comment]
Marking high priority and nominating for Sprint 9.

**Comment by pthiess** [comment]
@iwehrman

**Comment by bchintx** [comment]
Marking FBNC since pull request was merged.

**Comment by iwehrman** [comment]
I filed this, so I'm closing it. @larz0: please re-open if you aren't satisfied with the fix.
