### ISSUE TITLE
[Core][Browse dialog][Brackets]: The Browse dialog is clipped at the top.

### ISSUE THREAD

**Issue by julieyuan** [adobe/brackets-edge-web-fonts#158]
Steps:
1. Launch Brackets and install EWF extension (from which is under Avaliable tab on Extension Manager dialog, or from the URL:https://github.com/adobe/brackets-edge-web-fonts).
2. Open a css file and input `font-family:`
3. Press `Ctrl+Space` to bring up context menu, select: Browse Web Fonts...
4. It will pop up the Browse dialog and observe.

Result:
The dialog is at the top of the Brackets window, and it is clipped at the top. On my Win VM, even if I maximize Brackets window it still happens. On Mac, if I enlarge the Brackets window vertically, it still happens, but it will not happen if I maximize the window.

Expected:
The dialog should display well.

Notes: 
This issue not reproduce in Edge Code build 0.96.0-359083026.

ENV: MAC 10.9 and Win8.1 English OS
Build: 0.33.0-9858

Snapshot:
Please refer to snapshot for details:
![22222](https://f.cloud.github.com/assets/4251563/1341108/f4ac13de-3642-11e3-86cf-84008dcc79ad.jpg)

**Comment by dalcala** [comment]
I can repro this issue using Edge Code 0.97.0-359084096 on a Win 7 x86 VM & Win 8.1 x64 VM.  Seems to only repro if I make the Edge Code window not very tall (easy to do on a VM).

![ewf-158](https://f.cloud.github.com/assets/1512954/1579674/4a3fd648-51a3-11e3-8794-87b72399fd10.png)

**Comment by couzteau** [comment]
related git/edge/edge-code/issues/366

**Comment by couzteau** [comment]
Pushed updated SHA to EC with https://git.corp.adobe.com/edge/edge-code/pull/374

**Comment by dalcala** [comment]
Confirmed fixed using Edge Code build 0.97.0-359084113 on Win 7 x64 & Mac 10.8.5.  Closing.

**Comment by zhouweiwei1991** [comment]
Fixed in build 0.97.0-359084115.Here are snapshots for reference:
![0 97 0-359084115](https://f.cloud.github.com/assets/5466232/1588678/de2cb548-5256-11e3-95b7-af7b87b95b95.jpg)

**Comment by pthiess** [comment]
+1 nice work
