### ISSUE TITLE
Sizing issue when window undocked

### ISSUE THREAD

**Issue by anlawande** [adobe/brackets-edge-web-fonts#161]
Hi, I'm finding that when my brackets window is not fully maximized, the edge fonts popup is lost slightly on the above side.

I also recommend putting in a scroll bar. As by looking at it, it's not intuitive that there are more fonts to browse below.

![edgefonts](https://f.cloud.github.com/assets/4571767/1680015/67fd674a-5d65-11e3-9136-58ea42e1647f.jpg)

**Comment by redmunds** [comment]
I made a fix for that a couple weeks ago, so be sure you have the latest code for this extension.
