### ISSUE TITLE
Code hint menu is completely disabled

### ISSUE THREAD

**Issue by iwehrman** [adobe/brackets-edge-web-fonts#163]
To reproduce, place the cursor in a `font-family` value (for example; it seems to happen in other locations) and request code hints.

```
Uncaught TypeError: Cannot read property 'stack' of undefined cssModeSupport.js:46
inRuleBody cssModeSupport.js:46
FontParser.getFontTokenAtCursor fontParser.js:101
FontHints.hasHints main.js:262
(anonymous function) CodeHintManager.js:465
_beginSession CodeHintManager.js:464
_startNewSession CodeHintManager.js:515
Command.execute CommandManager.js:90
execute CommandManager.js:275
executeCommand ShellAPI.js:66
```

I'm on master everywhere: b71d15449ede700465de6652bcc77b41d2df0e96 in EWF e1c3b88191774447824d784faed5fbbdd9806219 in Brackets.

Marking this high priority since EWF code hints are completely broken. 

CC @couzteau

**Comment by couzteau** [comment]
confirming bug in Brackets master at `e1c3b88`
No bug in S35 release.

**Comment by redmunds** [comment]
FBNC back to @iwehrman

**Comment by iwehrman** [comment]
The menu works, but now it seems that the initial font scan and/or query-string filtering is broken. For example, in test/style.css I see this: 

!["filter"](http://cloud.wehrman.org/image/3R1N1j0v3f1b/Image%202014-01-28%20at%204.20.43%20PM.png)

Note that it's not picking up the adamina font. It also doesn't seem to be able to filter the "Abril-fatFace" value above, even though "abril-fatface" sometimes appears in the font list.

**Comment by RaymondLim** [comment]
@iwehrman I didn't see the issue you're seeing. Are you sure you have all the changes from that pull request? I made the last commit in that pull request that should fix the issue you're seeing.

**Comment by iwehrman** [comment]
I'm at cb8fe8bf715106074be8d43481d4af6459555285 on Brackets and cc63d99cf54951516a1828711fdbde6287a19223 in EWF.

**Comment by redmunds** [comment]
@iwehrman I saw that when testing. I assumed that it was not showing fonts that were already applied. Is that not how it worked before?

**Comment by iwehrman** [comment]
Ohhh yeah, that sounds right. OK then, LGTM.
