### ISSUE TITLE
Autocomplete menu shouldn't show the token you're currently typing

### ISSUE THREAD

**Issue by njx** [adobe/brackets-edge-web-fonts#17]
(Noticed this before but kind of didn't think of it as a bug, though it really is)
1. Type `font-family: arial;`
2. Put cursor before the semicolon
3. Type comma and space
   -> Code hint menu appears
4. Start typing a random word not in the menu

Actual result: The word you're typing shows up as the first match. 
Expected result: The word you're typing shouldn't get added to the menu.

**Comment by pthiess** [comment]
Sprint 14

**Comment by njx** [comment]
Fixed, closing.
