### ISSUE TITLE
[French] Menu layout issue for "Browse Web Fonts..."

### ISSUE THREAD

**Issue by ybayer** [adobe/brackets-edge-web-fonts#18]
1. Launch Brackets
2. Open a CSS file
3. Click a font and press Ctrl+Alt+Space

French translation for "Browse Web Fonts..." menu goes into two lines. Is it possible to make the popup wider?

https://www.dropbox.com/s/rnap0t3pewx8rkr/Browse_Web_Font.png

**Comment by ybayer** [comment]
Used with Brackets sprint14 0.14.0-3777 build

**Comment by joelrbrandt** [comment]
@njx @GarthDB Any opinion on this? We can't make the popup wider without messy changes to core.

I see two options: 
1. Make the font smaller in both English and French version
2. Live with the wrapping for now

**Comment by GarthDB** [comment]
it would be nice if we could make it longer - what about shortening the text by taking out the verb - Browse and just say Web Fonts?

**Comment by njx** [comment]
How bad would it be to just change it to "Web Fonts..." in French? "Les polices Web...", I guess.

**Comment by njx** [comment]
@GarthDB Jinx. I owe you a Coke.

**Comment by GarthDB** [comment]
you can "buy" me one from the fridge next week.

## 

Garth Braithwaite
Sent with Sparrow (http://www.sparrowmailapp.com)

**Comment by joelrbrandt** [comment]
Fixed in #31

**Comment by njx** [comment]
Fixed, ready to regress.

**Comment by joelrbrandt** [comment]
@ybayer We changed the French string from "Parcourir les polices Web..." to "Les polices Web Edge...". Does this seem okay? The shorter string prevents wrapping.

**Comment by ybayer** [comment]
Looks good to me. Asking the French reviewer for feedback.
https://www.dropbox.com/s/5x231uvqza5mnzh/Browse_Web_Font_new.png

**Comment by Tania-Jiacomini** [comment]
Hi, in this case it would be better to remove the determiner "Les", which is very uncommon in menu titles. Please change to "Polices Web Edge", this is meaningful enough. Thank you.

**Comment by Tania-Jiacomini** [comment]
It would also be necessary to apply this new translation to sprint14 experimental build 0.14.0-3834 - screenshot HOWTO_INSTRUCTIONS_2.jpg as well, see https://www.dropbox.com/s/l1mye3pzcqbok2o/EN_HOWTO_INSTRUCTIONS_2.jpg and https://www.dropbox.com/s/tewf77yfep3f0pb/FR_HOWTO_INSTRUCTIONS_2.jpg :

In the red square, "sélectionnez l’option Parcourir les polices Web" should be changed to "sélectionnez l’option Polices Web Edge". Thank you

**Comment by Tania-Jiacomini** [comment]
Plus, please note that CODEHINT_BROWSE.jpg screenshot provided for 2012-09-20_EdgeCode_LingTesting_Pass3 (sprint14 experimental build 0.14.0-3834) is the same as https://www.dropbox.com/s/5x231uvqza5mnzh/Browse_Web_Font_new.png and should be corrected accordingly.

Link to CODEHINT_BROWSE.jpg: https://www.dropbox.com/s/fzm1y4md0s5nq4k/CODEHINT_BROWSE.jpg

Thanks

**Comment by KamilJarocha** [comment]
Translations are changed to 'Polices Web Edge' in ALF as requested by Tania.

**Comment by joelrbrandt** [comment]
@KamilJarocha Thanks for your help! I don't yet see these in master (or in the repo at all). Will they be pushed later?

**Comment by ybayer** [comment]
@joelrbrandt ALF pushed to master just now.

**Comment by joelrbrandt** [comment]
Marking as FBNC and re-assigning to @ybayer for confirmation and closing.

**Comment by ybayer** [comment]
Confirmed the fix. Closing.

**Comment by Zhuyun** [comment]
@joelrbrandt 
Problem: French: the current menu display as "Edge Web Fonts" but not 'Polices Web Edge' as said above "Translations are changed to 'Polices Web Edge' in ALF as requested by Tania."

English is still "Browse Web Fonts".
Screenshot:
![web font](https://f.cloud.github.com/assets/2245172/106369/cb27267c-69f4-11e2-89cc-89ce3e3897fd.png)

Is 'Polices Web Edge' still the expected display for this menu?

**Comment by joelrbrandt** [comment]
@Zhuyun Thanks for bringing this up. The official name of the product is "Edge Web Fonts".

I don't remember the discussion around this translation that well, but I _think_ this is what happened. First, we went with the translation "Polices Web Edge" (which translates to "Edge Web Fonts"). But, people didn't like that because it is essentially translating the product name, which is something we do NOT do. Next, we changed it to the French translation of "Browse Web Fonts..." (which is the current English string). However, this translation was too long to fit in the dialog. So Finally, we decided to just go with the product name. And, since it was the product name, we chose not to translate it.

I'm happy to change it to whatever the LOC team thinks is most appropriate. Incidentally, the dialog is now wider, so the French translation of "Browse Web Fonts..." may fit.

**Comment by joelrbrandt** [comment]
@Zhuyun Looking back through the repository history, it appears that the translation we had for "Browse Web Fonts..." is "Parcourir les polices Web..."

That phrase _does_ fit in the new, wider dialog. So, we could go with this translation if that makes everyone happy.

**Comment by Zhuyun** [comment]
@joelrbrandt Thank you Joel. The story is we found this string is inconsistent between ENU and FRA. However it's good to know the translation of "Browse Web Fonts" can fit the wider dialog so that they become consistent on EN and FR UI.

We will check it in the latest build later then close this issue when fixed.

**Comment by ybayer** [comment]
@joelrbrandt It was a request from either Adam or Arno to keep the product name in translations so we changed the translation to "Edge Web Fonts..." from "Polices Web Edge...". Because the product name is translated in your suggested translation "Parcourir les polices Web...",  should I query the translation of "Browse Web Font..." in French. Does it sound okay?

**Comment by joelrbrandt** [comment]
@ybayer Yes, there was a request to not translate the product name.

The confusion here is this:

In English, the menu item does _not_ contain the product name. The English phrase is "Browse Web Fonts...". ("Web Fonts" is a general term, not the product name.)

When we first tried to translate this to French, the translation was too long to fit in the dialog (the translation of "Browse Web Fonts..." is "Parcourir les polices Web..."). So, then we went with a completely different phrase for French (which was the _untranslated_ product name). Confusing, I know!

Now, we've made the dialog wider. So, the translation of the English phrase into French _does_ fit. Therefore we have an opportunity to be more consistant. We can use "Browse Web Fonts..." in English and "Parcourir les polices Web..." in French, neither of which contain the product name.

The question is whether we want to make that change or not. I support it for consistency's sake. But I don't have a strong opinion.

**Comment by ybayer** [comment]
@joelrbrandt Thanks for the info! I agree to change for consistency. I'll fix in ALF.

**Comment by ybayer** [comment]
Fixed and pushed in master.

**Comment by joelrbrandt** [comment]
@Zhuyun Can you please confirm fixed and close?

@ybayer Thanks!

**Comment by Zhuyun** [comment]
Thank you both! Confirm fixed and closed.
![FR_Browse Web font_Brackets 20-0](https://f.cloud.github.com/assets/2245172/113447/53458a22-6b57-11e2-9a84-78cefdc6838e.png)
