### ISSUE TITLE
Font name appear incorrect in Browse Web Font

### ISSUE THREAD

**Issue by Zhuyun** [adobe/brackets-edge-web-fonts#23]
1. In Edge Code, Open the test folder in the Web Font file folder.
2. In the css file,  at the font-family value,  Press Command+Ctrl+Space on Mac to launch the Web Font list
3. Click 'Browse Web Fonts' to launch Web Font Extension dialog
4. Select 'Blackletter'
5. Check font name 'UnifrakturMaguntia'

Expected: the name should display right in the frame

Env: Win7 and MacOS X
Lang: English and French

Screenshots:
https://www.dropbox.com/s/yzczn7lfpzt2jvh/Blackletter_FontName.jpg?m

**Comment by joelrbrandt** [comment]
Temporary fix in #25. Longer term fix needed (filed as low priority bug #26)

**Comment by njx** [comment]
Temporary fix in place (by truncating for now), ready to regress.

**Comment by joelrbrandt** [comment]
@Zhuyun can you please confirm the fix when you have time? Thanks for filing this.

**Comment by Zhuyun** [comment]
Turns out truncated with build 3791 and newly downloaded EWF.

Screenshot:
https://www.dropbox.com/s/cgbigdvvolz8jfs/Blackletter_FontName_Truncation.jpg?m

**Comment by njx** [comment]
Yes, the truncation is intentional (as mentioned above)--it's the best we can do for now. We've filed #26 to track fixing it in a better way.

**Comment by Zhuyun** [comment]
Then shall I close this one?

**Comment by njx** [comment]
Yes please. Thanks!

**Comment by joelrbrandt** [comment]
@Zhuyun yes, I agree it's a bit strange that we're asking you to close a bug that isn't completely fixed. I guess the criteria for closing are a.) you believe the current solution is better than the initial problem, and b.) you believe that issue #26 accurately captures what needs to be done to fully fix the bug.

If you agree with "a" and "b", it'd be great if you would close the bug. If not, it would be great to hear your thoughts.

Thanks for your help!

**Comment by Zhuyun** [comment]
Truely understand. Thank you both! #26 is tracking this.
