### ISSUE TITLE
The sample fonts truncated on the browse web fonts page

### ISSUE THREAD

**Issue by Zhanxin** [adobe/brackets-edge-web-fonts#24]
Steps:
1. Configure the web fonts files
2. Launch the Edge Code application
3. Open a css file, at the font-family value, press Alt+Ctrl+Space on Windows to launch the Web Font list
4. Click "Browse Web Fonts..."

Result: The sample fonts display on the page are truncated

Expect: Complete sample fonts can be displayed.

Env: Win7; Mac
Language: ENU

Screenshot:
https://www.dropbox.com/s/4qwab3zv4f2cpf6/WebFontTruncate.jpg

**Comment by joelrbrandt** [comment]
Fix in #25. The EWF service just re-rendered all their preview tiles with more padding.

**Comment by njx** [comment]
Fixed, ready to regress.

**Comment by joelrbrandt** [comment]
@Zhanxin can you please confirm the fix when you have time? Thanks for filing this.

**Comment by Zhanxin** [comment]
Verify this issue with build 0.14.1-3872, fixed. Close this issue.
