### ISSUE TITLE
dynamically truncate font names that are too long for detail area

### ISSUE THREAD

**Issue by joelrbrandt** [adobe/brackets-edge-web-fonts#26]
Right now, we have overflow: hidden for the font details section of each font. A few font names are too long and get clipped.

Long term, we should dynamically compute the length, and add ellipses instead.

**Comment by iwehrman** [comment]
Surely @couzteau can knock this one right off!

**Comment by joelrbrandt** [comment]
@couzteau you _might_ be able to fix this in about 30 seconds with something like:

``` css
#theDiv {
  overflow:hidden;
  text-overflow:ellipsis;
}
```

http://www.w3schools.com/cssref/css3_pr_text-overflow.asp

Or... I might be totally wrong.

**Comment by iwehrman** [comment]
@joelrbrandt Yes, after we get rid of the Browse Web Fonts stub.
