### ISSUE TITLE
"Browse Web Fonts..." menu item can be positioned offscreen

### ISSUE THREAD

**Issue by gruehle** [adobe/brackets-edge-web-fonts#27]
The logic for keeping the code hint menu fully onscreen doesn't account for the "Browse Web Fonts..." item. If you are code hinting a font-family rule near the bottom of the screen, the code hint menu is cut off.

Steps to repro:
1. Copy the contents of this gist into a css file: https://gist.github.com/0ca229798bdcc9f68dc1
2. Resize the window so you see just the top pixel of the "44" line number
3. Open code hints for the font-family rule on line 32

Results:
"Browse Web Fonts..." menu item is cutoff and cannot be clicked

Screenshot:
![Screenshot Image](https://dl.dropbox.com/u/17644987/MenuCutoff.png)

**Comment by gruehle** [comment]
The likelihood of running into this bug is _very_ low, since there is only a 2-3 pixel variance in window size where this occurs. If you make the window any smaller, the code hint menu moves up; if you make the window larger, the item is no longer cutoff.

**Comment by njx** [comment]
Marking low-priority

**Comment by iwehrman** [comment]
We have full faith in @couzteau on this one.
