### ISSUE TITLE
Cannot get to Browse Web Fonts with down arrow key and therefore cannot invoke it without a mouse click.

### ISSUE THREAD

**Issue by RaymondLim** [adobe/brackets-edge-web-fonts#35]
After invoking EWF by typing a space character, you can use down/up arrow key to reach the font already available in the list. But you cannot reach to the last item (Browse Web Fonts...) with down arrow key and thus you cannot add a web font without a mouse click.

**Comment by njx** [comment]
This is a known limitation of the current implementation--currently the plugin is hacking a new DOM node into the menu. Longer term, we should consider whether we should add a way  for code hint plugins to add arbitrary items to the code hint dropdown.

**Comment by iwehrman** [comment]
Over to @couzteau! You're doing the lord's work, here!
