### ISSUE TITLE
Browse Web Fonts dialog has several keyboard accessibility issues.

### ISSUE THREAD

**Issue by RaymondLim** [adobe/brackets-edge-web-fonts#36]
## ~~Issue 1~~

Bring up the Web Fonts dialog and set focus in the Search field. Press Shift-Tab. 

Result: You can't see where the focus goes. You can scroll down the font list and still cannot locate the selected font.
## ~~Issue 2~~

Set focus back in Search field and hit Tab key. Focus goes to the first button in font category. Try to press down arrow key. 

Result: Nothing happens. If you hit tab key, then focus moves to the next font category button. The correct design should have all font category buttons acting like a list. ie. respond to down/up arrow keys to switch font category. Home/End keys may be a plus, but not a must. Tab key should set focus to the first font on the right.
## ~~Issue 3~~

~~Search field does not have the initial focus and there is no way to set focus in there without a mouse.~~
## ~~Issue 4~~

Cannot navigate font with keyboard even if you have click on one of them.

**Comment by joelrbrandt** [comment]
I agree that these are definitely all issues. However, we don't currently have focus management in modals. This is on the backlog in trello: https://trello.com/c/ldcN6BbD

It will be hard to fix these just in the extension. We really need the above story to be complete before we can do this right.

**Comment by iwehrman** [comment]
Re-assigning to @couzteau. (Sucker!)

**Comment by iwehrman** [comment]
Part 3 is fixed at least...

**Comment by iwehrman** [comment]
And parts 1, 2 and 4 are addressed by #121.

**Comment by iwehrman** [comment]
FBNC to @RaymondLim.

**Comment by couzteau** [comment]
now possible to select any font by keyboard navigation only. tabbing works fine. cursor keys behave predictably and in a useful way. closing
