### ISSUE TITLE
Script tag text field should not have resize handle on bottom right corner.

### ISSUE THREAD

**Issue by RaymondLim** [adobe/brackets-edge-web-fonts#37]
1. Insert a web font in a css file.
2. Click on the Wf button to generate the required script tag.

Result: You will see the resize handle at the bottom right corner of the script tag field. If you grab it and resize, you can drag it outside of the dialog.

**Comment by joelrbrandt** [comment]
I'm not exactly sure how to fix this. In #4, @njx suggested making the text field read-only. I agree that this removes the distracting blue border. However, it a.) does _not_ remove the resize handle, and b.) causes the mouse cursor to display a big "no" symbol on OS X when the user hovers. This seems less than ideal.

Does anyone have suggestions?

**Comment by joelrbrandt** [comment]
Based on this: http://stackoverflow.com/questions/588089/hiding-textarea-resize-handle-in-safari It looks like we can set `resize: none` in the CSS to fix the issue @RaymondLim raises.

And, it looks like we can do `cursor: pointer` to fix the "no" cursor

**Comment by joelrbrandt** [comment]
Marking FBNC and assigning to @RaymondLim for regressing.

**Comment by RaymondLim** [comment]
Nice job! You fixed two issues.
