### ISSUE TITLE
Focus rectangle for font category button may not show all the edges.

### ISSUE THREAD

**Issue by RaymondLim** [adobe/brackets-edge-web-fonts#39]
1. Bring up the Browse Web Fonts dialog and set focus in Search text field.
2. Hit Tab key so that focus is on the very first font category button.

Result: The bottom edge of the focus highlight is missing.

**Comment by iwehrman** [comment]
Yep, this looks terrible! 

![Focus border bug](http://f.cl.ly/items/1H2e3x0W2q3n0X2U3F3e/Screen%20Shot%202013-04-10%20at%205.11.27%20PM.png)

**Comment by iwehrman** [comment]
Fixed by #97.
