### ISSUE TITLE
Extension never loads if user is not connected to Internet at application launch time

### ISSUE THREAD

**Issue by joelrbrandt** [adobe/brackets-edge-web-fonts#41]
Right now, the extension makes one request for the entire font list at app launch time. If it can't complete this request, it fails gracefully and the extension never loads.

Ideally, we should keep retrying at some (fairly long) interval, and load the extension when we can.

The code contains a TODO about this in `main.js`

**Comment by iwehrman** [comment]
Beaten to death.
