### ISSUE TITLE
Can't display all fonts at once due to potential crash

### ISSUE THREAD

**Issue by joelrbrandt** [adobe/brackets-edge-web-fonts#42]
If we get into a situation where we're trying to display all fonts at once, there's a potential for a crash. This is because CEF can run out of available FDs.

This is a bug in Chrome, filed here:
  https://code.google.com/p/chromium/issues/detail?id=151039

So far, this has only reproduced on Lion. We've modified the search algorithm so that it's hard to display all the fonts. But, it's possible that if lots of FDs were open for some other reason, even displaying a smaller number of fonts could cause a problem.

Adding this bug mostly to track the fix of the Chrome issue.

**Comment by iwehrman** [comment]
That Chromium bug has been closed without a fix, and I can't figure out how to reproduce the crash. Any hints?

**Comment by joelrbrandt** [comment]
The only way I'm aware of to reproduce it is to install Lion (it doesn't repro on ML), and then change the EWF source so that it displays all fonts when the dialog initially loads.

Alternatively, you could just make a simple webpage that dynamically (i.e. with JS) adds a whole bunch of images to the DOM at the same time, and then set the shell location to that file. The cause of the bug was that CEF would open up a ton of file descriptors all at the same time, would hit an OS limit, and then would crash.

You can see/change how many open file descriptors are allowed on your system with `ulimit -n [new limit]`. I think the limit is only on a per-process basis, though, so I'm not sure (without some googling) how you'd change the limit for CEF for experimentation (esp. given that CEF is multi-process).

**Comment by joelrbrandt** [comment]
Update: Child processes _seem_ to inherit the limit of their parent process. If I do:

``` bash
ulimit -n 257
bash
ulimit -n
```

I get 257 in the child bash process. So, you could set the limit to something small, launch Brackets from the shell, and see what happens!

**Comment by iwehrman** [comment]
Yeaaaah, I think we'll just go ahead and close this one out then.

If you have to change the source and install an old OS to reproduce this then I think we can safely ignore it for now. Please re-open if you ever see this again.
