### ISSUE TITLE
Edge Web Fonts fails to load if OS locale is German

### ISSUE THREAD

**Issue by peterflynn** [adobe/brackets-edge-web-fonts#45]
Two users have reported this problem in the forums:
http://forums.adobe.com/thread/1072264?tstart=0

The "Wf" icon simply fails to show up.  In the console, these errors appear:

```
Failed to load resource ...www/extensions/default/EdgeWebFonts/nls/de/strings.js

Uncaught Error: Load timeout for modules: i18n!nls/strings nls/de/strings
```

I think the problem is that EdgeWebFonts\nls\strings.js lists "de" as a supported language, but no "de" folder is actually present.

**Comment by redmunds** [comment]
FBNC back to @peterflynn

**Comment by joelrbrandt** [comment]
@peterflynn Just a reminder: once this is confirmed fixed and closed, we need to update the SHA in Edge Code. Normally, I'd be happy to do it, but I'll likely be on PTO when you close this. Thanks!

**Comment by joelrbrandt** [comment]
@peterflynn I created a pull in Edge Code to update the SHA. This bug should be fixed. Assigned to you to confirm and close.

Thanks!

**Comment by joelrbrandt** [comment]
This has been fixed for a loooooong time. Closing.
