### ISSUE TITLE
handleSelect API now requires to return true to close the code hints.

### ISSUE THREAD

**Issue by RaymondLim** [adobe/brackets-edge-web-fonts#47]
In Sprint 16, we made a change in this api, and all extensions using Code Complete APIs need to update their handleSelect API to return true.

**Comment by njx** [comment]
@RaymondLim -- could you make sure a note about that API change gets added to https://github.com/adobe/brackets/wiki/Release-Notes:-Sprint-16 ? Thanks.

**Comment by RaymondLim** [comment]
Thanks. I just add it.

**Comment by joelrbrandt** [comment]
@RaymondLim I created pull #48 to address this. Might you have time to review?

**Comment by joelrbrandt** [comment]
FBNC, assigned back to @RaymondLim 

Thanks!
