### ISSUE TITLE
Should add ", " when inserting before existing item

### ISSUE THREAD

**Issue by njx** [adobe/brackets-edge-web-fonts#5]
1. Open main.css from the starter project
2. Click before the " in "Helvetica Neue"
3. Bring up the EWF dialog and choose a font

Result: The font name is inserted, but with no ", " after it. It would be nice if we were smart and inserted that automatically when there are other font names on the line after the cursor.

**Comment by iwehrman** [comment]
I'll bet @couzteau is chomping at the bit to fix this one.

**Comment by couzteau** [comment]
verified.

**Comment by pthiess** [comment]
Moved out to Sprint 5 as suggested by @couzteau.

**Comment by couzteau** [comment]
PR https://github.com/adobe/brackets-edge-web-fonts/pull/143 fixes the issue

**Comment by couzteau** [comment]
submitted new PR.

**Comment by joelrbrandt** [comment]
![giphy](https://f.cloud.github.com/assets/908679/972457/4dae2afc-05fc-11e3-94b2-26cf5b69c6af.gif)

**Comment by couzteau** [comment]
@joelrbrandt :)
