### ISSUE TITLE
Web font hints should show up right after typing ``font-family:``

### ISSUE THREAD

**Issue by RaymondLim** [adobe/brackets-edge-web-fonts#55]
Try to type `font-family:` inside a css rule. After typing the colon, web font hints does not automatically show up.  You have to explicitly invoke it with Ctrl-Space.

**Comment by joelrbrandt** [comment]
This is now fixed. Assigning to @RaymondLim for closing

**Comment by joelrbrandt** [comment]
Confirming fixed and closing.
