### ISSUE TITLE
[FRA]: Some tooltips are not localized in the Edge Web Fonts page.

### ISSUE THREAD

**Issue by dil77307** [adobe/brackets-edge-web-fonts#59]
Steps：
1. Launch the Brackets sprint19 5290
2. Open a css file and move the mouse behind the font-family, press"Ctrl+Space"
3. Click "Edge Web Fonts..."
4. Move the mouse stay on the left icons
5. Check the below tooltip:
Headings, Paragraphs, Script, Blackletter, Handmade, Decorative

Results:
Some tooltips are not localized.

Expect:
These tooltips should be localized in French.

Screenshot:

![Tooltips_Not localized](https://f.cloud.github.com/assets/3336842/92998/6fa2b4ca-6606-11e2-8a1d-7dff8463f643.jpg)

**Comment by joelrbrandt** [comment]
@dil77307 Thanks for raising this issue. When we did the initial translation, I know that our translation team explicitly chose NOT to translate these. However, I do not remember the reasoning.

I'll follow up with them again to see if they've changed their stance.

**Comment by joelrbrandt** [comment]
@dil77307 A quick update: our localization team is handling this and there will be a fix in the next release of Edge Code. (And, master will be updated shortly.) Thanks for pointing this out!

**Comment by ArturOledzki** [comment]
Strings have been corrected in ALF:
Headings -> Titres
Paragraphs -> Paragraphes
Script -> Cursive
Blackletter -> Gothique
Handmade -> Manuscrite
Decorative  -> Décorative

**Comment by MWereli** [comment]
Japanese translation will follow on Monday - translator did not make it on time, due to time zone difference.

**Comment by ybayer** [comment]
Please make sure to match with the translation in Typekit.
French: https://typekit.com/fonts?locale=fr_FR
Japanese: https://typekit.com/fonts?locale=ja_JP

**Comment by ybayer** [comment]
French file has been checked in
https://github.com/adobe/brackets-edge-web-fonts/blob/master/nls/fr/strings.js

**Comment by joelrbrandt** [comment]
Confirming fixed in master and closing.

**Comment by dil77307** [comment]
Confirm fixed, the tooltips has been localized as suggestion. 
Please refer to the screenshot below:
![Tooltip_fixed](https://f.cloud.github.com/assets/3336842/109663/2ccd4832-6a8d-11e2-9056-6cd15a98f705.jpg)
