### ISSUE TITLE
The link "Terms of Use" cannot be opened in Edge Web Fonts dialog .

### ISSUE THREAD

**Issue by Chen-Dandan** [adobe/brackets-edge-web-fonts#64]
1. Launch Brackets Sprint 20 version 0.20.0-0 (Make sure Web fonts file package "brackets-edge-web-fonts-master" has been put in Extension folder)
2. Click the "Wf" icon on the right-top corner.
3. Click the "Terms of Use" link in Adobe Edge Web Fonts dialog.

Result: The page linked to "Terms of Use" cannot be opened.

Expected: The link should be opened successfully.

Notes: Repro on Mac and Windows. Repro on EN.

**Comment by ryanstewart** [comment]
Hi Chen, I can't get this to reproduce. Does the link just not do anything for you when you click it?

**Comment by Chen-Dandan** [comment]
@ryanstewart 
Hi Ryan, I reproduced this issue in China Mainland rather than in Adobe VPN.  If I am in Adobe VPN, this link can be opened successfully. 
Also, when you click on "Terms of Use", it linked to http://adobe.com/go/edgewebfonts_tou, but can't be opened.
![link](https://f.cloud.github.com/assets/2245186/113927/82fb58b6-6b82-11e2-8d40-545da2a26986.png)

**Comment by joelrbrandt** [comment]
@Chen-Dandan @ryanstewart This sounds like a firewall issue. Should we close this bug?

**Comment by Zhuyun** [comment]
Don't know why the link works with Firefox but not for IE&Chrome. Close on behalf of Dandan Chen.
