### ISSUE TITLE
Hints don't appear automatically unless you code-complete 'font-family'

### ISSUE THREAD

**Issue by peterflynn** [adobe/brackets-edge-web-fonts#69]
1. Open the latest EC preview 3 build
2. Open main.css in the Getting Started content
3. Make a new line inside the 'body' rule
4. Type `font-family:` (optional: and hit space)

Result: No EWF hints pop up

Expected: In preview 1 & 2, hints pop up at this point

Workaround:
- Don't type 'font-family' yourself: type it partway, then hit Enter to accept the property name code hint.  Then the EWF font hints will automatically appear (and they'll stick around if you hit space).
- Type the first letter of any _standard_ font name -- then the hints will appear (filtered to that letter).  This only works with letters that have matches though (e.g. "x" will not cause hints to pop up).
- Or explicitly hit Ctrl+Space -- that still shows the hints properly as well.

**Comment by peterflynn** [comment]
Updated title/description to clarify that this doesn't happen when using CSS code hints to "type" the property name.

**Comment by redmunds** [comment]
This was done intentionally to be more minimalistic as css code hints now are. As soon as you type a single letter, they pop up.

Note that if you choose font-family from the hints list, you will get the EWF dialog popped up at that point.

Do you think this is significantly different than CSS code hints, or were you just expecting it to behave the same as last time you used it?

**Comment by peterflynn** [comment]
Ok, good point -- I confirm it pops up as soon as you type a letter too.  I'll add that to the workarounds & lower the priority.  Doesn't seem like it should block EC.

I'll leave the bug open though since I think this is a case where we _might_ want to consider popping up right away.  After typing a “:” it seems pretty safe to pop up CSS value hints without being over-aggressive... unlike CSS property hints, there's not that much ambiguity here -- the user is basically guaranteed to either type a value, or a space and then a value... and that's about it).

**Comment by peterflynn** [comment]
One other note: these hints pop up _less_ than the core Brackets CSS value hints.  In core Brackets, if I type a property name and then colon [\+ space], the hints popup that appeared while I was typing the property name remains open and now shows property values.  With EWF this isn't true: the property name popup closes when I type colon.

**Comment by iwehrman** [comment]
I don't think this is a bug. The behavior of EWF in this context seems correct. The true bug, IMO, is that CSS value hints open as soon as you type the colon. That, I think, is far too aggressive.

**Comment by iwehrman** [comment]
In any case, I'll assign this to myself to either fix or take responsibility for closing after talking it over with the rest of the EC team.

**Comment by iwehrman** [comment]
Addressed by adobe/brackets#3848.

**Comment by iwehrman** [comment]
Fixed by adobe/brackets#3848. Closing.
