### ISSUE TITLE
Font filtering no longer works if you have the cursor in a font starts with a capital letter.

### ISSUE THREAD

**Issue by RaymondLim** [adobe/brackets-edge-web-fonts#71]
1. Open main.css page from Getting Started project.
2. Set cursor inside the font-family rule right after one of the fonts starts with a capital letter (eg. after "A" in Arial).
3. Press Ctrl+Space to bring up EWF hints.

Result: You dont see the font list is filtered with the letters before the cursor. If you change the capital letter to lowercase, then you will see the filtering with some bold letters in each code hint.

**Comment by joelrbrandt** [comment]
Fixed with #72, assigning to @RaymondLim for closing.

**Comment by joelrbrandt** [comment]
Confirming fixed and closing.
