### ISSUE TITLE
Loc: FRA: Image in WF dialog is in English

### ISSUE THREAD

**Issue by Zhuyun** [adobe/brackets-edge-web-fonts#73]
Method:
1. Launch Brackets
2. Click on the WF icon in the up right corner

Result:
The pop-up WF dialog is localized in French but the image used English images.

Expected:
Should use French image.

Env: Win&Mac
Build: 0.20.0-5678
Screenshot:
![EWF_Introduction_Image_unloc](https://f.cloud.github.com/assets/2245172/170851/a7c61a6c-7a7f-11e2-86ed-cbcb5a43352e.jpg)

**Comment by pthiess** [comment]
The images need to be updated @iwehrman

**Comment by iwehrman** [comment]
[This file](https://github.com/adobe/brackets-edge-web-fonts/blob/master/img/ewf-howto-dialog.png) needs to be updated and localized.

**Comment by pthiess** [comment]
@GarthDB - not sure if you had time for updating the images soon, even the English version seems out of date? Assuming you could recreate it - right? @joelrbrandt Would you have the original image?

**Comment by joelrbrandt** [comment]
@adrocknaphobia created this image. I do not have access to the original.

**Comment by ryanstewart** [comment]
I think we need @Zhuyun to verify it's fixed for us. But if not I can verify the fix and close today.

**Comment by iwehrman** [comment]
This works for me now. Marking FBNC.

**Comment by Zhuyun** [comment]
Verified in build sprint24 7097 on Win&Mac. Fixed then closed.
![EWF_Win7_24_7097](https://f.cloud.github.com/assets/2245172/424023/56068116-ad7a-11e2-883e-2dd4ee1dc7a3.jpg)
![EWF_Mac_24_7097](https://f.cloud.github.com/assets/2245172/424025/5b5a3432-ad7a-11e2-905a-cdccb8090dd6.png)
