### ISSUE TITLE
code hint window can get positioned partially off screen

### ISSUE THREAD

**Issue by joelrbrandt** [adobe/brackets-edge-web-fonts#77]
![Screen Shot 2013-03-27 at 6 21 05 AM](https://f.cloud.github.com/assets/908679/308185/4c11dc78-96e1-11e2-9a87-b7e66aa4f203.png)

**Steps to reproduce**
1. Create a CSS file with a `font-family` rule that goes almost to the edge of the window.
2. Put cursor at the end and invoke the hint dialog

**Result**
Because of the hack that resizes the code hint window, it can get partially positioned off screen

**Expected**
Moved to stay onscreen after the resize hack

Note: This happens both with and without word wrap

**Comment by ryanstewart** [comment]
Similar to #27.

**Comment by iwehrman** [comment]
You can do it, @couzteau!
