### ISSUE TITLE
No font-family code hinting UI in <style> element. No Edge Fonts. Edit

### ISSUE THREAD

**Issue by ryanstewart** [adobe/brackets-edge-web-fonts#81]
From https://github.com/adobe/brackets/issues/3359

When authoring inside a 'style' element in the .html file there is no code hinting for font families. Because of this, a user cannot get the UI to pick custom fonts from Edge Fonts. There is no problem when authoring in .css files.

**Comment by iwehrman** [comment]
Assigning to @couzteau
