### ISSUE TITLE
Retina-compatible how-to image

### ISSUE THREAD

**Issue by iwehrman** [adobe/brackets-edge-web-fonts#87]
As mentioned in #86, these images should be retina-compatible: 

![How-to](https://raw.github.com/adobe/brackets-edge-web-fonts/master/img/ewf-howto-dialog-en.png)

![How-to fr](https://raw.github.com/adobe/brackets-edge-web-fonts/master/img/ewf-howto-dialog-fr.png)

@ryanstewart might have the resources handy to make the double-resolution images.

**Comment by iwehrman** [comment]
Might want to roll this into the "make EWF better" user story.

**Comment by iwehrman** [comment]
@bchintx Can you verify and close? (It sure looks fixed to me.)

**Comment by bchintx** [comment]
Looks good on my non-retina devices.  The French screenshot appears on French Windows, too.
