### ISSUE TITLE
New Icon for Edge Web Fonts in Right Sidebar

### ISSUE THREAD

**Issue by ryanstewart** [adobe/brackets-edge-web-fonts#91]
@larz0 has created new icons for Edge Web fonts that will replace the old icon. 
![webfonts_icon 2x](https://f.cloud.github.com/assets/45450/433418/bc57c2ec-aecc-11e2-9d1d-9c6ff1ad3539.png)
![webfonts_icon](https://f.cloud.github.com/assets/45450/433419/bc56ad30-aecc-11e2-82a8-44093f596937.png)

**Comment by iwehrman** [comment]
Fixed by #92.
